name: Weather Analytics Pipeline

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */2 * * *' 

permissions:
  contents: write

jobs:
  weather-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create config.json
        run: cp config/config_template.json config/config.json
    
      - name: Inject API Key
        run: sed -i "s/OPENWEATHER_API_KEY/${{ secrets.OPENWEATHER_API_KEY }}/g" config/config.json

      - name: Run Pipeline
        run: python scripts/master_pipeline.py

      - name: Run Validation Tests
        run: |
          pytest tests -v

      - name: Check Existing Database
        run: |
          ls -lh database

      - name: Count Existing Rows
        run: |
          python - <<EOF
          import sqlite3
          conn = sqlite3.connect("database/weather.db")
          cur = conn.cursor()
          cur.execute("SELECT COUNT(*) FROM weather_observations")
          print("ROWS BEFORE PIPELINE:", cur.fetchone()[0])
          conn.close()
          EOF

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: logs/
      
      - name: Commit Database and Power BI Dataset
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add database/weather.db
          git add powerbi/weather_dataset.csv

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update weather analytics data"
          fi

      - name: Upload Power BI Dataset
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: powerbi-dataset
          path: powerbi/weather_dataset.csv

      - name: Push Changes
        run: |
          git push origin main
